-- SELECT * FROM actors;
-- SELECT COUNT(*) FROM actors;
-- INSERT INTO actors (first_name, last_name, age, number_oscars)
-- VALUES('Oussama','08/10/1970', 5);
-- It shows this message : ERROR:  INSERT has more target columns than expressions
-- LINE 3: INSERT INTO actors (first_name, last_name, age, number_oscar...
